block.settings.layout_builder_view_block:*:
  type: block_settings
  label: "Entity Browser block"
  mapping:
    label_display:
      type: boolean
      label: Label Display
    view_mode:
      type: string
      label: "Allowed View Modes"
    offset:
      type: number
      label: Offset
